services:
  - type: web
    name: xpeer
    env: node
    buildCommand: npm install && cd server && npx prisma db push && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
